### ISSUE TITLE
It does nothing when I run the command

### ISSUE THREAD

**Issue by agarrharr** [gillstrom/screensaver#2]
I installed it and the `screensaver --help` command works, but the `screensaver` command just switches me into another directory. I'm not sure what's going on here.

<img width="469" alt="screen shot 2015-10-25 at 3 55 59 pm" src="https://cloud.githubusercontent.com/assets/3266363/10718135/fb607000-7b30-11e5-9868-6f18cef0c862.png">

**Comment by gillstrom** [comment]
Thanks for reporting, what os are you using?

**Comment by agarrharr** [comment]
I'm on OS X El Capitan 10.11.1, Macbook Pro Late 2013.

**Comment by gillstrom** [comment]
What happens if you try `open -a ScreenSaverEngine`?

**Comment by agarrharr** [comment]
I just upgraded to nvm v4.2.1 and it works now. I was on version 0.12.7.
